# Generated by Django 4.1.5 on 2023-02-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to='pdfs/'),
        ),
    ]
