# Generated by Django 4.1.5 on 2023-02-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.CharField(default='', max_length=110),
        ),
    ]
